# INTRODUCTION TO NUMPY

# Install NumPy

pip install numpy

# Import NumPy

In [2]:
import numpy as np

# Checking NumPy Version

In [3]:

import numpy as np
print(np.__version__)


2.3.1


# Sample code without Numpy

In [5]:
import time

python_list = list(range(1000000))

start_time = time.time()

result = 0
for x in python_list:
    result += (x**2 + x**3 + x**4)

end_time = time.time()
print(f"Python Loop Time Taken: {end_time - start_time: .6f} seconds")


Python Loop Time Taken:  0.293711 seconds


# Sample code with numpy

In [1]:
import numpy as np
import time

numpy_arr = np.arange(1000000, dtype=np.float64)
start_time = time.time()

np_result = np.sum(numpy_arr**2 + numpy_arr**3 + numpy_arr**4)

end_time = time.time()
print(f"Numpy time taken: {end_time - start_time:.6f} seconds")


Numpy time taken: 0.049065 seconds


# Creating a numpy array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(type(arr))

<class 'numpy.ndarray'>


# Creating a range of numbers

In [7]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


# Changing the shape of an array

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))

print(reshaped)

[[1 2 3]
 [4 5 6]]


# Accessing elements using indexing

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 2])

6


# Joining arrays

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6 7 8]


# Sorting arrays

In [3]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
sorted_arr = np.sort(arr)

print(sorted_arr)

[1 2 3 4 5 6 7 8]


# Removing single elements

In [ ]:
arr = np.array([10, 20, 30, 40])
new_arr = np.delete(arr, 1)
print(new_arr)

[10 30 40]


# Removing multiple elements

In [11]:
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

print("remaining elements after deleting 1st and last element ",
      np.delete(arr1, [0, 4]))

[1 2 3 4 5]
remaining elements after deleting 1st and last element  [2 3 4]


# Removing a column in a 2D array

In [17]:
arr = np.array([[1 ,2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print(np.delete(arr, 1, axis=1))

[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]


# Removing a row in a 2D array

In [18]:
arr = np.array([[1 ,2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print(np.delete(arr, 1, axis=0))

[[ 1  2  3  4]
 [ 9 10 11 12]]


# Properties of arrays

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:")
print(a)

print("Type:", type(a))
print("Shape:", a.shape)
print("Data Type:", a.dtype)
print("Number of Dimensions:", a.ndim)
print("Total Elements:", a.size)
print("Item Size (bytes):", a.itemsize)
print("Total Bytes:", a.nbytes)

Array:
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)
Data Type: int64
Number of Dimensions: 2
Total Elements: 6
Item Size (bytes): 8
Total Bytes: 48


# Broadcasting

In [5]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([10, 20 , 30])

result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]


# Arithmetic Operations

In [3]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_1 / array_2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


# Comparison Operations

In [6]:
array1 = np.array([20, 30, 40, 50])
print(array1 < 35)

[ True  True False False]


In [7]:
array1 = np.array([9, 12, 21])
array2 = np.array([21, 12, 9])

result = np.less(array1, array2)
print("Using less():",result)

result = np.less_equal(array1, array2)
print("Using less_equal():",result)

result = np.greater(array1, array2)
print("Using greater():",result)

result = np.greater_equal(array1, array2)
print("Using greater_equal():",result)

result = np.equal(array1, array2)
print("Using equal():",result)

result = np.not_equal(array1, array2)
print("Using not_equal():",result)

Using less(): [ True False False]
Using less_equal(): [ True  True False]
Using greater(): [False False  True]
Using greater_equal(): [False  True  True]
Using equal(): [False  True False]
Using not_equal(): [ True False  True]


# Logical Operations

In [7]:
arr1 = np.array([1, 2, 3, 4, 5])
np.logical_and(arr1 > 1, arr1 < 5)

array([False,  True,  True,  True, False])

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])

and_result = np.logical_and(array1 > 1, array1 < 5)
print("AND result:", and_result)
print("Values (1 < x < 5):", array1[and_result])

or_result = np.logical_or(array1 < 2, array1 > 4)
print("OR result:", or_result)
print("Values (x < 2 or x > 4):", array1[or_result])

not_result = np.logical_not(array1 > 3)
print("NOT result:", not_result)
print("Values (NOT x > 3):", array1[not_result])

AND result: [False  True  True  True False]
Values (1 < x < 5): [2 3 4]
OR result: [ True False False False  True]
Values (x < 2 or x > 4): [1 5]
NOT result: [ True  True  True False False]
Values (NOT x > 3): [1 2 3]


# Matrix Multiplication Sample

In [1]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Method 1: Using @ operator (recommended)
C = A @ B

# Method 2: Using np.dot()
D = np.dot(A, B)

print("Result (A @ B):\n", C)
print("Result using np.dot():\n", D)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Result (A @ B):
 [[19 22]
 [43 50]]
Result using np.dot():
 [[19 22]
 [43 50]]


# In-Place Operations

In [4]:
arr = np.array([1, 2, 3])
arr += 5
print(arr)

[6 7 8]
