# INTRODUCTION TO NUMPY

## Install NumPy

pip install numpy

## Import NumPy

In [ ]:
import numpy as np

## Checking NumPy Version

In [3]:

import numpy as np
print(np.__version__)


2.3.1


## Creating a NumPy Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(type(arr))

<class 'numpy.ndarray'>


## Matrix Multiplication Sample

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


## Conditional

In [5]:
a = np.array([20, 30, 40, 50])
print(a < 35) 

[ True  True False False]


## Logical

In [ ]:
x = np.array([True, False, True])
y = np.array([False, False, True])

print(x & y)  # Logical AND
print(x | y)  # Logical OR
print(~x)     # Logical NOT

[False False  True]
[ True False  True]
[False  True False]


In [ ]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_1 / array_2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [6]:
a = np.array([[1, 2], [3, 4]])
a*=2
print(a)

[[2 4]
 [6 8]]


## Properties of Arrays

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:")
print(a)

print("Type:", type(a))           # <class 'numpy.ndarray'>
print("Shape:", a.shape)          # (2, 3)
print("Data Type:", a.dtype)      # int64 or int32 (platform-dependent)
print("Number of Dimensions:", a.ndim)  # 2
print("Total Elements:", a.size)        # 6
print("Item Size (bytes):", a.itemsize) # typically 4 or 8
print("Total Bytes:", a.nbytes)         # size × itemsize


Array:
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)
Data Type: int64
Number of Dimensions: 2
Total Elements: 6
Item Size (bytes): 8
Total Bytes: 48


## Accessing elements using Indexing

In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[1, 2])

6


## Adding Arrays

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6 7 8]


## Removing single elements

In [12]:
arr = np.array([10, 20, 30, 40])
new_arr = np.delete(arr, 1)  # Removes index 1 (20)
print(new_arr)  # [10 30 40]

[10 30 40]


## Removing multiple elements

In [16]:
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

print("remaining elements after deleting 1st and last element ",
      np.delete(arr1, [0, 4]))

[1 2 3 4 5]
remaining elements after deleting 1st and last element  [2 3 4]


## Removing a column in a 2D array

In [17]:
arr = np.array([[1 ,2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print(np.delete(arr, 1, axis=1))

[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]


## Removing a row in a 2D array

In [18]:
arr = np.array([[1 ,2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print(np.delete(arr, 1, axis=0))

[[ 1  2  3  4]
 [ 9 10 11 12]]


## Sorting Arrays

In [11]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
sorted_arr = np.sort(arr)

print(sorted_arr)

[1 2 3 4 5 6 7 8]
